# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import awards.models
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedCostSchedule',
            fields=[
                ('id', models.BigIntegerField(unique=True, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=30)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(awards.models.EASUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ATPAuditTrail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('award', models.IntegerField()),
                ('modification', models.CharField(max_length=100)),
                ('workflow_step', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(null=True, blank=True)),
                ('date_completed', models.DateTimeField(null=True, blank=True)),
                ('assigned_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('status', models.IntegerField(default=0, choices=[(0, b'New'), (1, b'Award Intake'), (2, b'Award Negotiation'), (3, b'Award Setup'), (4, b'Subaward & Award Management'), (5, b'Award Closeout'), (6, b'Complete')])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('extracted_to_eas', models.BooleanField(default=False)),
                ('subaward_done', models.BooleanField(default=False)),
                ('award_management_done', models.BooleanField(default=False)),
                ('send_to_modification', models.BooleanField(default=False)),
                ('send_to_setup', models.BooleanField(default=False)),
                ('common_modification', models.BooleanField(default=False)),
                ('award_dual_negotiation', models.BooleanField(default=False)),
                ('award_dual_setup', models.BooleanField(default=False)),
                ('award_dual_modification', models.BooleanField(default=False)),
                ('award_acceptance_user', models.ForeignKey(related_name='+', verbose_name=b'Award Intake User', to=settings.AUTH_USER_MODEL)),
                ('award_closeout_user', models.ForeignKey(related_name='+', verbose_name=b'Award Closeout User', to=settings.AUTH_USER_MODEL)),
                ('award_management_user', models.ForeignKey(related_name='+', verbose_name=b'Award Management User', to=settings.AUTH_USER_MODEL)),
                ('award_modification_user', models.ForeignKey(related_name='+', verbose_name=b'Award Modification User', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('award_negotiation_user', models.ForeignKey(related_name='+', verbose_name=b'Award Negotiation User', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('award_setup_user', models.ForeignKey(related_name='+', verbose_name=b'Award Setup User', to=settings.AUTH_USER_MODEL)),
                ('subaward_user', models.ForeignKey(related_name='+', verbose_name=b'Subaward User', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AwardAcceptance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(verbose_name=b'Comments', blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created', null=True)),
                ('current_modification', models.BooleanField(default=True)),
                ('eas_status', models.CharField(blank=True, max_length=2, verbose_name=b'EAS status', choices=[(b'A', b'Active'), (b'OH', b'On hold'), (b'AR', b'At risk'), (b'C', b'Closed')])),
                ('new_funding', models.NullBooleanField(verbose_name=b'New Funding?')),
                ('fcoi_cleared_date', models.DateField(null=True, verbose_name=b'FCOI cleared date', blank=True)),
                ('phs_funded', models.NullBooleanField(verbose_name=b'PHS funded?')),
                ('award_setup_priority', models.CharField(blank=True, max_length=2, verbose_name=b'Award Setup Priority', choices=[(b'on', 1), (b'tw', 2), (b'th', 3), (b'fo', 4), (b'fi', 5), (b'ni', 9)])),
                ('priority_by_director', models.NullBooleanField(verbose_name=b'Prioritized by Director?')),
                ('project_title', models.CharField(max_length=250, verbose_name=b'Project Title (if different from Proposal)', blank=True)),
                ('foreign_travel', models.NullBooleanField(verbose_name=b'Foreign Travel?')),
                ('f_a_rate', models.CharField(max_length=250, verbose_name=b'F&A rate', blank=True)),
                ('full_f_a_recovery', models.NullBooleanField(verbose_name=b'Full F&A Recovery?')),
                ('explanation', models.CharField(max_length=250, verbose_name=b'If no full F&A, provide explanation', blank=True)),
                ('mfa_investigators', models.NullBooleanField(verbose_name=b'MFA investigators?')),
                ('admin_establishment', models.NullBooleanField(verbose_name=b'Administrative establishment?')),
                ('award_issue_date', models.DateField(null=True, blank=True)),
                ('award_acceptance_date', models.DateField(null=True, blank=True)),
                ('agency_award_number', models.CharField(max_length=50, blank=True)),
                ('sponsor_award_number', models.CharField(max_length=50, verbose_name=b'Prime Award # (if GW is subawardee)', blank=True)),
                ('award_total_costs', models.DecimalField(null=True, verbose_name=b'Total award costs', max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs', models.DecimalField(null=True, verbose_name=b'Total award direct costs', max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs', models.DecimalField(null=True, verbose_name=b'Total award indirect costs', max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y1', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y1', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y1', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y2', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y2', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y2', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y3', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y3', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y3', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y4', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y4', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y4', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y5', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y5', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y5', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y6', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y6', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y6', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y7', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y7', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y7', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y8', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y8', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y8', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y9', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y9', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y9', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_total_costs_y10', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_direct_costs_y10', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('award_indirect_costs_y10', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('contracting_official', models.CharField(max_length=500, verbose_name=b'GMO or CO', blank=True)),
                ('gmo_co_phone_number', models.CharField(max_length=15, verbose_name=b'GMO/CO phone number', blank=True)),
                ('gmo_co_email', models.CharField(max_length=50, verbose_name=b'GMO/CO email', blank=True)),
                ('pta_modification', models.NullBooleanField(verbose_name=b'Do you want to send this to the post-award team for modification?')),
                ('acceptance_completion_date', models.DateTimeField(null=True, verbose_name=b'Completion Date', blank=True)),
                ('award', models.ForeignKey(to='awards.Award')),
            ],
            options={
                'verbose_name': 'Award intake',
                'verbose_name_plural': 'Award intakes',
            },
            bases=(awards.models.AwardModificationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AwardCloseout',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(verbose_name=b'Comments', blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('date_assigned', models.DateTimeField(null=True, verbose_name=b'Date Assigned', blank=True)),
                ('closeout_completion_date', models.DateTimeField(null=True, verbose_name=b'Completion Date', blank=True)),
                ('award', models.OneToOneField(to='awards.Award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardManagement',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(verbose_name=b'Comments', blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('date_assigned', models.DateTimeField(null=True, verbose_name=b'Date Assigned', blank=True)),
                ('management_completion_date', models.DateTimeField(null=True, verbose_name=b'Completion Date', blank=True)),
                ('award', models.OneToOneField(to='awards.Award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardManager',
            fields=[
                ('id', models.BigIntegerField(unique=True, serialize=False, primary_key=True)),
                ('full_name', models.CharField(max_length=240)),
                ('gwid', models.CharField(max_length=150, null=True, verbose_name=b'GWID', blank=True)),
                ('system_user', models.BooleanField()),
                ('end_date', models.DateField(null=True, blank=True)),
                ('active', models.BooleanField()),
                ('title', models.CharField(max_length=64, null=True, blank=True)),
                ('first_name', models.CharField(max_length=64, blank=True)),
                ('middle_name', models.CharField(max_length=32, blank=True)),
                ('last_name', models.CharField(max_length=64, blank=True)),
                ('phone', models.CharField(max_length=32, null=True, blank=True)),
                ('email', models.CharField(max_length=64, null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(awards.models.EASUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AwardModification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(verbose_name=b'Comments', blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('date_assigned', models.DateTimeField(null=True, verbose_name=b'Date Assigned', blank=True)),
                ('short_name', models.CharField(max_length=30, verbose_name=b'Award short name', blank=True)),
                ('start_date', models.DateField(null=True, blank=True)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('final_reports_due_date', models.DateField(null=True, verbose_name=b'Final Reports/Final Invoice Due Date (Close Date)', blank=True)),
                ('eas_award_type', models.CharField(blank=True, max_length=2, verbose_name=b'EAS award type', choices=[(b'C', b'Contract'), (b'G', b'Grant'), (b'I', b'Internal Funding'), (b'PP', b'Per Patient'), (b'PA', b'Pharmaceutical')])),
                ('sp_type', models.CharField(blank=True, max_length=3, verbose_name=b'SP Type', choices=[(b'SP1', b'SP1 - Research and Development'), (b'SP2', b'SP2 - Training'), (b'SP3', b'SP3 - Other'), (b'SP4', b'SP4 - Clearing and Suspense'), (b'SP5', b'SP5 - Program Income')])),
                ('property_equip_code', models.CharField(blank=True, max_length=2, verbose_name=b'T&C: Property and Equipment Code', choices=[(b'TG', b'Title to GW'), (b'TS', b'Title to Sponsor'), (b'TD', b'Title to be determined at purchase'), (b'SE', b'Special EAS Value')])),
                ('onr_administered_code', models.CharField(blank=True, max_length=2, verbose_name=b'T&C: ONR Administered Code', choices=[(b'Y', b'Yes, Administered'), (b'N', b'No, Administered')])),
                ('cost_sharing_code', models.CharField(blank=True, max_length=2, verbose_name=b'T&C: Cost Sharing Code', choices=[(b'M', b'Mandatory'), (b'V', b'Voluntary'), (b'B', b'Both')])),
                ('bill_to_address', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=150, verbose_name=b'Contact Name (Last, First)', blank=True)),
                ('phone', models.CharField(max_length=50, blank=True)),
                ('billing_events', models.TextField(blank=True)),
                ('document_number', models.CharField(max_length=100, blank=True)),
                ('date_wait_for_updated', models.DateTimeField(null=True, verbose_name=b'Date Wait for Updated', blank=True)),
                ('wait_for_reson', models.CharField(blank=True, max_length=2, verbose_name=b'Wait for', choices=[(b'RB', b'Revised Budget'), (b'PA', b'PI Access'), (b'CA', b'Cost Share Approval'), (b'FC', b'FCOI'), (b'PS', b'Proposal Submission'), (b'SC', b'Sponsor Clarity'), (b'NO', b'New Org needed'), (b'IC', b'Internal Clarification'), (b'DC', b'Documents not in GW Docs')])),
                ('nine_ninety_form_needed', models.NullBooleanField(verbose_name=b'990 Form Needed?')),
                ('task_location', models.CharField(blank=True, max_length=2, choices=[(b'AL', b'AL - ALEXANDRIA'), (b'BE', b'BE - BETHESDA'), (b'CC', b'CC - CRYSTAL CITY'), (b'CL', b'CL - CLARENDON'), (b'CM', b"CM - ST MARY'S COUNTY, CALIFORNIA, MD"), (b'CW', b'CW - K STREET CENTER OFF-CAMPUS DC'), (b'DE', b'DE - DISTANCE EDUCATION'), (b'FB', b'FB - FOGGY BOTTOM'), (b'FC', b'FC - CITY OF FALLS CHURCH'), (b'FX', b'FX - FAIRFAX COUNTY'), (b'GS', b'GS - GODDARD SPACE FLIGHT CENTER'), (b'HR', b'HR - HAMPTON ROADS'), (b'IN', b'IN - INTERNATIONAL'), (b'LA', b'LA - LANGLEY AIR FORCE BASE'), (b'LO', b'LO - LOUDOUN COUNTY OTHER'), (b'MV', b'MV - MOUNT VERNON CAMPUS'), (b'OA', b'OA - OTHER ARLINGTON COUNTY'), (b'OD', b'OD - OTHER DISTRICT OF COLUMBIA'), (b'OG', b'OG - OTHER MONTGOMERY COUNTY'), (b'OM', b'OM - OTHER MARYLAND'), (b'OV', b'OV - OTHER VIRGINIA'), (b'PA', b'PA - PACE - Classes at Sea'), (b'RI', b'RI - RICHMOND, CITY OF'), (b'RO', b'RO - ROSSLYN ARLINGTON COUNTY'), (b'RV', b'RV - ROCKVILLE'), (b'SM', b'SM - SUBURBAN MARYLAND'), (b'T', b'T - TOTAL LOCATION'), (b'US', b'US - OTHER US'), (b'VC', b'VC - VIRGINIA CAMPUS'), (b'VR', b'VR - VIRGINIA RESEARCH AND TECHNOLOGY CENTER'), (b'VS', b'VS - VIRGINIA SQUARE')])),
                ('performance_site', models.CharField(blank=True, max_length=2, choices=[(b'ON', b'On-campus'), (b'OF', b'Off-campus'), (b'OT', b'Other')])),
                ('expanded_authority', models.NullBooleanField(verbose_name=b'Expanded Authority?')),
                ('financial_reporting_req', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=14, verbose_name=b'Financial Reporting Requirements', choices=[(b'MN', b'Monthly'), (b'QR', b'Quarterly'), (b'SA', b'Semi-annually'), (b'AN', b'Annually'), (b'OT', b'Other (specify)')])),
                ('financial_reporting_oth', models.CharField(max_length=250, verbose_name=b'Other financial reporting requirements', blank=True)),
                ('technical_reporting_req', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=14, verbose_name=b'Technical Reporting Requirements', choices=[(b'MN', b'Monthly'), (b'QR', b'Quarterly'), (b'SA', b'Semi-annually'), (b'AN', b'Annually'), (b'OT', b'Other (specify)')])),
                ('technical_reporting_oth', models.CharField(max_length=250, verbose_name=b'Other technical reporting requirements', blank=True)),
                ('patent_reporting_req', models.DateField(null=True, verbose_name=b'Patent Report Requirement', blank=True)),
                ('invention_reporting_req', models.DateField(null=True, verbose_name=b'Invention Report Requirement', blank=True)),
                ('property_reporting_req', models.DateField(null=True, verbose_name=b'Property Report Requirement', blank=True)),
                ('equipment_reporting_req', models.DateField(null=True, verbose_name=b'Equipment Report Requirement', blank=True)),
                ('budget_restrictions', models.NullBooleanField(verbose_name=b'Budget Restrictions?')),
                ('award_setup_complete', models.DateField(null=True, verbose_name=b'Award Setup Complete', blank=True)),
                ('qa_screening_complete', models.DateField(null=True, verbose_name=b'QA Screening Complete', blank=True)),
                ('pre_award_spending_auth', models.NullBooleanField(verbose_name=b'Pre-award spending authorized?')),
                ('record_destroy_date', models.DateField(null=True, verbose_name=b'Record Retention Destroy Date', blank=True)),
                ('ready_for_eas_setup', models.CharField(blank=True, max_length=3, verbose_name=b'Ready for EAS Setup?', choices=[(b'Y', b'Yes'), (b'N', b'No'), (b'M', b'Manual')])),
                ('modification_completion_date', models.DateTimeField(null=True, verbose_name=b'Completion Date', blank=True)),
                ('wait_for', models.TextField(blank=True)),
                ('allowed_cost_schedule', models.ForeignKey(blank=True, to='awards.AllowedCostSchedule', null=True)),
                ('award', models.ForeignKey(to='awards.Award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardNegotiation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(verbose_name=b'Comments', blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('date_assigned', models.DateTimeField(null=True, verbose_name=b'Date Assigned', blank=True)),
                ('current_modification', models.BooleanField(default=True)),
                ('subcontracting_plan', models.NullBooleanField(verbose_name=b'Is Small Business Subcontracting Plan required?')),
                ('under_master_agreement', models.NullBooleanField(verbose_name=b'Under Master Agreement?')),
                ('award_type', models.CharField(blank=True, max_length=3, verbose_name=b'Award Type', choices=[(b'CR', b'Contract: Cost-reimbursable'), (b'FP', b'Contract: Fixed price'), (b'TM', b'Contract: Time & materials'), (b'GC', b'Grant: Cost-reimbursable'), (b'GF', b'Grant: Fixed amount award'), (b'CA', b'Cooperative agreement'), (b'CD', b'CRADA'), (b'ND', b'NDA'), (b'TA', b'Teaming agreement'), (b'DU', b'DUA'), (b'RF', b'RFP'), (b'MT', b'MTA'), (b'MA', b'Master agreement'), (b'OT', b'Other')])),
                ('other_award_type', models.CharField(max_length=255, blank=True)),
                ('related_other_agreements', models.NullBooleanField(verbose_name=b'Related Other Agreements?')),
                ('related_other_comments', models.TextField(verbose_name=b'Related other agreements comments', blank=True)),
                ('negotiator', models.CharField(max_length=500, verbose_name=b'Negotiator Assist', blank=True)),
                ('date_received', models.DateField(null=True, verbose_name=b'Date Received', blank=True)),
                ('retention_period', models.CharField(max_length=500, verbose_name=b'Sponsor Retention Period', blank=True)),
                ('gw_doesnt_own_ip', models.NullBooleanField(verbose_name=b"GW Doesn't Own IP?")),
                ('gw_background_ip', models.NullBooleanField(verbose_name=b'GW Background IP?')),
                ('negotiation_status', models.CharField(default=b'IQ', max_length=3, verbose_name=b'Negotiation Status', blank=True, choices=[(b'IQ', b'In queue'), (b'IP', b'In progress'), (b'WFS', b'Waiting for sponsor'), (b'WFP', b'Waiting for PI'), (b'WFO', b'Waiting for other department'), (b'CD', b'Completed'), (b'UD', b'Unrealized')])),
                ('negotiation_notes', models.TextField(verbose_name=b'Negotiation Notes', blank=True)),
                ('foreign_restrictions', models.NullBooleanField(verbose_name=b'Foreign Participation Restrictions?')),
                ('certificates_insurance', models.NullBooleanField(verbose_name=b'Certificate of Insurance Needed?')),
                ('insurance_renewal', models.DateField(null=True, verbose_name=b'Certificate of Insurance Renewal Date', blank=True)),
                ('government_property', models.NullBooleanField(verbose_name=b'Government Furnished Property?')),
                ('data_security_restrictions', models.NullBooleanField(verbose_name=b'Data/Security Restrictions?')),
                ('everify', models.NullBooleanField(verbose_name=b'E-verify?')),
                ('publication_restriction', models.NullBooleanField(verbose_name=b'Publication Restriction?')),
                ('negotiation_completion_date', models.DateTimeField(null=True, verbose_name=b'Completion Date', blank=True)),
                ('award', models.ForeignKey(to='awards.Award')),
            ],
            options={
                'abstract': False,
            },
            bases=(awards.models.AwardModificationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AwardOrganization',
            fields=[
                ('id', models.BigIntegerField(unique=True, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=240)),
                ('organization_type', models.CharField(max_length=30, null=True, blank=True)),
                ('org_info1_meaning', models.CharField(max_length=80)),
                ('org_info2_meaning', models.CharField(max_length=80)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(awards.models.EASUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AwardSetup',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(verbose_name=b'Comments', blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('date_assigned', models.DateTimeField(null=True, verbose_name=b'Date Assigned', blank=True)),
                ('short_name', models.CharField(max_length=30, verbose_name=b'Award short name', blank=True)),
                ('start_date', models.DateField(null=True, blank=True)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('final_reports_due_date', models.DateField(null=True, verbose_name=b'Final Reports/Final Invoice Due Date (Close Date)', blank=True)),
                ('eas_award_type', models.CharField(blank=True, max_length=2, verbose_name=b'EAS award type', choices=[(b'C', b'Contract'), (b'G', b'Grant'), (b'I', b'Internal Funding'), (b'PP', b'Per Patient'), (b'PA', b'Pharmaceutical')])),
                ('sp_type', models.CharField(blank=True, max_length=3, verbose_name=b'SP Type', choices=[(b'SP1', b'SP1 - Research and Development'), (b'SP2', b'SP2 - Training'), (b'SP3', b'SP3 - Other'), (b'SP4', b'SP4 - Clearing and Suspense'), (b'SP5', b'SP5 - Program Income')])),
                ('property_equip_code', models.CharField(blank=True, max_length=2, verbose_name=b'T&C: Property and Equipment Code', choices=[(b'TG', b'Title to GW'), (b'TS', b'Title to Sponsor'), (b'TD', b'Title to be determined at purchase'), (b'SE', b'Special EAS Value')])),
                ('onr_administered_code', models.CharField(blank=True, max_length=2, verbose_name=b'T&C: ONR Administered Code', choices=[(b'Y', b'Yes, Administered'), (b'N', b'No, Administered')])),
                ('cost_sharing_code', models.CharField(blank=True, max_length=2, verbose_name=b'T&C: Cost Sharing Code', choices=[(b'M', b'Mandatory'), (b'V', b'Voluntary'), (b'B', b'Both')])),
                ('bill_to_address', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=150, verbose_name=b'Contact Name (Last, First)', blank=True)),
                ('phone', models.CharField(max_length=50, blank=True)),
                ('billing_events', models.TextField(blank=True)),
                ('document_number', models.CharField(max_length=100, blank=True)),
                ('date_wait_for_updated', models.DateTimeField(null=True, verbose_name=b'Date Wait for Updated', blank=True)),
                ('wait_for_reson', models.CharField(blank=True, max_length=2, verbose_name=b'Wait for', choices=[(b'RB', b'Revised Budget'), (b'PA', b'PI Access'), (b'CA', b'Cost Share Approval'), (b'FC', b'FCOI'), (b'PS', b'Proposal Submission'), (b'SC', b'Sponsor Clarity'), (b'NO', b'New Org needed'), (b'IC', b'Internal Clarification'), (b'DC', b'Documents not in GW Docs')])),
                ('nine_ninety_form_needed', models.NullBooleanField(verbose_name=b'990 Form Needed?')),
                ('task_location', models.CharField(blank=True, max_length=2, choices=[(b'AL', b'AL - ALEXANDRIA'), (b'BE', b'BE - BETHESDA'), (b'CC', b'CC - CRYSTAL CITY'), (b'CL', b'CL - CLARENDON'), (b'CM', b"CM - ST MARY'S COUNTY, CALIFORNIA, MD"), (b'CW', b'CW - K STREET CENTER OFF-CAMPUS DC'), (b'DE', b'DE - DISTANCE EDUCATION'), (b'FB', b'FB - FOGGY BOTTOM'), (b'FC', b'FC - CITY OF FALLS CHURCH'), (b'FX', b'FX - FAIRFAX COUNTY'), (b'GS', b'GS - GODDARD SPACE FLIGHT CENTER'), (b'HR', b'HR - HAMPTON ROADS'), (b'IN', b'IN - INTERNATIONAL'), (b'LA', b'LA - LANGLEY AIR FORCE BASE'), (b'LO', b'LO - LOUDOUN COUNTY OTHER'), (b'MV', b'MV - MOUNT VERNON CAMPUS'), (b'OA', b'OA - OTHER ARLINGTON COUNTY'), (b'OD', b'OD - OTHER DISTRICT OF COLUMBIA'), (b'OG', b'OG - OTHER MONTGOMERY COUNTY'), (b'OM', b'OM - OTHER MARYLAND'), (b'OV', b'OV - OTHER VIRGINIA'), (b'PA', b'PA - PACE - Classes at Sea'), (b'RI', b'RI - RICHMOND, CITY OF'), (b'RO', b'RO - ROSSLYN ARLINGTON COUNTY'), (b'RV', b'RV - ROCKVILLE'), (b'SM', b'SM - SUBURBAN MARYLAND'), (b'T', b'T - TOTAL LOCATION'), (b'US', b'US - OTHER US'), (b'VC', b'VC - VIRGINIA CAMPUS'), (b'VR', b'VR - VIRGINIA RESEARCH AND TECHNOLOGY CENTER'), (b'VS', b'VS - VIRGINIA SQUARE')])),
                ('performance_site', models.CharField(blank=True, max_length=2, choices=[(b'ON', b'On-campus'), (b'OF', b'Off-campus'), (b'OT', b'Other')])),
                ('expanded_authority', models.NullBooleanField(verbose_name=b'Expanded Authority?')),
                ('financial_reporting_req', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=14, verbose_name=b'Financial Reporting Requirements', choices=[(b'MN', b'Monthly'), (b'QR', b'Quarterly'), (b'SA', b'Semi-annually'), (b'AN', b'Annually'), (b'OT', b'Other (specify)')])),
                ('financial_reporting_oth', models.CharField(max_length=250, verbose_name=b'Other financial reporting requirements', blank=True)),
                ('technical_reporting_req', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=14, verbose_name=b'Technical Reporting Requirements', choices=[(b'MN', b'Monthly'), (b'QR', b'Quarterly'), (b'SA', b'Semi-annually'), (b'AN', b'Annually'), (b'OT', b'Other (specify)')])),
                ('technical_reporting_oth', models.CharField(max_length=250, verbose_name=b'Other technical reporting requirements', blank=True)),
                ('patent_reporting_req', models.DateField(null=True, verbose_name=b'Patent Report Requirement', blank=True)),
                ('invention_reporting_req', models.DateField(null=True, verbose_name=b'Invention Report Requirement', blank=True)),
                ('property_reporting_req', models.DateField(null=True, verbose_name=b'Property Report Requirement', blank=True)),
                ('equipment_reporting_req', models.DateField(null=True, verbose_name=b'Equipment Report Requirement', blank=True)),
                ('budget_restrictions', models.NullBooleanField(verbose_name=b'Budget Restrictions?')),
                ('award_setup_complete', models.DateField(null=True, verbose_name=b'Award Setup Complete', blank=True)),
                ('qa_screening_complete', models.DateField(null=True, verbose_name=b'QA Screening Complete', blank=True)),
                ('pre_award_spending_auth', models.NullBooleanField(verbose_name=b'Pre-award spending authorized?')),
                ('record_destroy_date', models.DateField(null=True, verbose_name=b'Record Retention Destroy Date', blank=True)),
                ('ready_for_eas_setup', models.CharField(blank=True, max_length=3, verbose_name=b'Ready for EAS Setup?', choices=[(b'Y', b'Yes'), (b'N', b'No'), (b'M', b'Manual')])),
                ('wait_for', models.TextField(blank=True)),
                ('setup_completion_date', models.DateTimeField(null=True, verbose_name=b'Completion Date', blank=True)),
                ('allowed_cost_schedule', models.ForeignKey(blank=True, to='awards.AllowedCostSchedule', null=True)),
                ('award', models.OneToOneField(to='awards.Award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardTemplate',
            fields=[
                ('id', models.BigIntegerField(unique=True, serialize=False, primary_key=True)),
                ('number', models.CharField(max_length=15)),
                ('short_name', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['number'],
            },
            bases=(awards.models.EASUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CFDANumber',
            fields=[
                ('flex_value', models.CharField(max_length=150, unique=True, serialize=False, primary_key=True)),
                ('description', models.CharField(max_length=240)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['flex_value'],
            },
            bases=(awards.models.EASUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EASMapping',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('interface', models.CharField(default=b'C', max_length=1, choices=[(b'C', b'Cayuse'), (b'L', b'Lotus')])),
                ('field', models.CharField(max_length=50)),
                ('incoming_value', models.CharField(max_length=250)),
                ('atp_model', models.CharField(max_length=50)),
                ('atp_pk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FedNegRate',
            fields=[
                ('flex_value', models.CharField(max_length=150, unique=True, serialize=False, primary_key=True)),
                ('description', models.CharField(max_length=240)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['description'],
            },
            bases=(awards.models.EASUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('report', models.CharField(blank=True, max_length=2, choices=[(b'FT', b'Final Technical'), (b'FP', b'Final Progress Report'), (b'FD', b'Final Deliverable(s)'), (b'IP', b'Final Invention/Patent'), (b'FI', b'Final Invention'), (b'FP', b'Final Property'), (b'FE', b'Final Equipment')])),
                ('due_date', models.DateField(null=True, blank=True)),
                ('submitted_date', models.DateField(null=True, blank=True)),
                ('award', models.ForeignKey(to='awards.Award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigIntegerField(unique=True, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['number'],
            },
            bases=(awards.models.EASUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IndirectCost',
            fields=[
                ('id', models.BigIntegerField(unique=True, serialize=False, primary_key=True)),
                ('rate_schedule', models.CharField(max_length=30)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['rate_schedule'],
            },
            bases=(awards.models.EASUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KeyPersonnel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('employee_id', models.CharField(max_length=40, verbose_name=b'Emp ID', blank=True)),
                ('last_name', models.CharField(max_length=64, blank=True)),
                ('first_name', models.CharField(max_length=64, blank=True)),
                ('middle_name', models.CharField(max_length=32, blank=True)),
                ('project_role', models.CharField(max_length=128, blank=True)),
                ('calendar_months', models.DecimalField(null=True, verbose_name=b'Calendar mos.', max_digits=5, decimal_places=3, blank=True)),
                ('academic_months', models.DecimalField(null=True, verbose_name=b'Academic mos.', max_digits=5, decimal_places=3, blank=True)),
                ('summer_months', models.DecimalField(null=True, verbose_name=b'Summer mos.', max_digits=5, decimal_places=3, blank=True)),
                ('effort', models.CharField(max_length=10, blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NegotiationStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('negotiation_status', models.CharField(blank=True, max_length=50, choices=[(b'IQ', b'In queue'), (b'IP', b'In progress'), (b'WFS', b'Waiting for sponsor'), (b'WFP', b'Waiting for PI'), (b'WFO', b'Waiting for other department'), (b'CD', b'Completed'), (b'UD', b'Unrealized')])),
                ('negotiation_status_changed_user', models.CharField(max_length=100, blank=True)),
                ('negotiation_notes', models.TextField(blank=True)),
                ('negotiation_status_date', models.DateTimeField(null=True, blank=True)),
                ('award', models.ForeignKey(to='awards.Award')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceSite',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ps_organization', models.CharField(max_length=255, verbose_name=b'Organization', blank=True)),
                ('ps_duns', models.BigIntegerField(null=True, verbose_name=b'DUNS', blank=True)),
                ('ps_street1', models.CharField(max_length=255, verbose_name=b'Street 1', blank=True)),
                ('ps_street2', models.CharField(max_length=255, verbose_name=b'Street 2', blank=True)),
                ('ps_city', models.CharField(max_length=255, verbose_name=b'City', blank=True)),
                ('ps_state', models.CharField(max_length=100, verbose_name=b'State', blank=True)),
                ('ps_zipcode', models.CharField(max_length=128, verbose_name=b'Zip', blank=True)),
                ('ps_country', models.CharField(max_length=128, verbose_name=b'Country', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimeSponsor',
            fields=[
                ('id', models.BigIntegerField(unique=True, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(awards.models.EASUpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PriorApproval',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('request', models.CharField(blank=True, max_length=2, choices=[(b'AB', b'Absence or Change of Key Personnel'), (b'CF', b'Carry-forward of unexpended balances to subsequent funding periods'), (b'CS', b'Change in Scope'), (b'ER', b'Effort Reduction'), (b'EN', b'Equipment not in approved budget'), (b'FC', b'Faculty consulting compensation that exceeds base salary'), (b'FT', b'Foreign Travel'), (b'IN', b'Initial no-cost extension of up to 12 months (per competitive segment)'), (b'OT', b'Other'), (b'RA', b'Rebudgeting among budget categories'), (b'RB', b'Rebudgeting between direct and F&A costs'), (b'RF', b'Rebudgeting of funds allotted for training (direct payment to trainees) to other categories of expense'), (b'SN', b'Subsequent no-cost extension or extention of more than 12 months')])),
                ('date_submitted', models.DateField(null=True, blank=True)),
                ('status', models.CharField(blank=True, max_length=2, choices=[(b'PN', b'Pending'), (b'AP', b'Approved'), (b'NA', b'Not Approved')])),
                ('date_approved', models.DateField(null=True, blank=True)),
                ('award', models.ForeignKey(to='awards.Award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(verbose_name=b'Comments', blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('dummy', models.BooleanField(default=False)),
                ('is_first_proposal', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created', null=True)),
                ('lotus_id', models.CharField(max_length=20, blank=True)),
                ('employee_id', models.CharField(max_length=40, verbose_name=b'Employee ID', blank=True)),
                ('proposal_id', models.BigIntegerField(unique=True, null=True, verbose_name=b'Proposal ID', blank=True)),
                ('proposal_number', models.CharField(max_length=50, null=True, verbose_name=b'Proposal Number', blank=True)),
                ('proposal_title', models.CharField(max_length=256, verbose_name=b'Internal Proposal Title', blank=True)),
                ('proposal_type', models.CharField(max_length=256, blank=True)),
                ('lotus_department_code', models.CharField(max_length=128, blank=True)),
                ('division_name', models.CharField(max_length=150, blank=True)),
                ('is_subcontract', models.CharField(max_length=10, verbose_name=b'Is this a subcontract?', blank=True)),
                ('tracking_number', models.CharField(max_length=15, verbose_name=b'Grants.gov tracking number', blank=True)),
                ('project_start_date', models.DateField(null=True, blank=True)),
                ('project_end_date', models.DateField(null=True, blank=True)),
                ('submission_date', models.DateField(null=True, blank=True)),
                ('sponsor_deadline', models.DateField(null=True, blank=True)),
                ('lotus_agency_name', models.CharField(max_length=250, blank=True)),
                ('project_title', models.CharField(max_length=256, blank=True)),
                ('agency_type', models.CharField(max_length=256, blank=True)),
                ('application_type_code', models.CharField(max_length=25, verbose_name=b'Kind of application', blank=True)),
                ('federal_identifier', models.CharField(max_length=256, verbose_name=b'Previous Grant #', blank=True)),
                ('is_change_in_grantee_inst', models.CharField(max_length=10, verbose_name=b'Change in grantee institution?', blank=True)),
                ('project_type', models.CharField(max_length=256, blank=True)),
                ('responsible_entity', models.CharField(max_length=256, blank=True)),
                ('departmental_id_primary', models.CharField(max_length=256, verbose_name=b'Departmental ID primary', blank=True)),
                ('departmental_id_secondary', models.CharField(max_length=256, verbose_name=b'Departmental ID secondary', blank=True)),
                ('departmental_name_primary', models.CharField(max_length=256, blank=True)),
                ('departmental_name_secondary', models.CharField(max_length=256, blank=True)),
                ('are_vertebrate_animals_used', models.CharField(max_length=10, verbose_name=b'Are vertebrate animals used?', blank=True)),
                ('is_iacuc_review_pending', models.CharField(max_length=10, verbose_name=b'Is IACUC review pending?', blank=True)),
                ('iacuc_protocol_number', models.CharField(max_length=256, verbose_name=b'IACUC protocol number', blank=True)),
                ('iacuc_approval_date', models.DateField(null=True, verbose_name=b'IACUC approval date', blank=True)),
                ('are_human_subjects_used', models.CharField(max_length=10, verbose_name=b'Are human subjects used?', blank=True)),
                ('is_irb_review_pending', models.CharField(max_length=10, verbose_name=b'Is IRB review pending?', blank=True)),
                ('irb_protocol_number', models.CharField(max_length=256, verbose_name=b'IRB protocol number', blank=True)),
                ('irb_review_date', models.DateField(null=True, verbose_name=b'IRB review date', blank=True)),
                ('is_haz_mat', models.CharField(max_length=10, verbose_name=b'Uses hazardous materials', blank=True)),
                ('budget_first_per_start_date', models.DateField(null=True, verbose_name=b'Budget first period start date', blank=True)),
                ('budget_first_per_end_date', models.DateField(null=True, verbose_name=b'Budget first period end date', blank=True)),
                ('cost_shr_mand_is_committed', models.CharField(max_length=10, blank=True)),
                ('cost_shr_mand_amount', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('cost_shr_mand_source', models.CharField(max_length=256, blank=True)),
                ('cost_shr_vol_is_committed', models.CharField(max_length=10, blank=True)),
                ('cost_shr_vol_amount', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('cost_shr_vol_source', models.CharField(max_length=256, blank=True)),
                ('will_involve_foreign_nationals', models.CharField(max_length=10, blank=True)),
                ('will_involve_shipment', models.CharField(max_length=10, blank=True)),
                ('will_involve_foreign_contract', models.CharField(max_length=10, blank=True)),
                ('total_costs', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y1', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y2', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y3', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y4', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y5', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y6', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y7', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y8', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y9', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_costs_y10', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y1', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y2', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y3', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y4', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y5', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y6', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y7', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y8', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y9', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_direct_costs_y10', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y1', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y2', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y3', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y4', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y5', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y6', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y7', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y8', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y9', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('total_indirect_costs_y10', models.DecimalField(null=True, max_digits=15, decimal_places=2, blank=True)),
                ('agency_name', models.ForeignKey(blank=True, to='awards.FundingSource', null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, blank=True, to='awards.Award', null=True)),
                ('department_name', models.ForeignKey(verbose_name=b'Department Code & Name', blank=True, to='awards.AwardOrganization', null=True)),
                ('principal_investigator', models.ForeignKey(verbose_name=b'Principal Investigator', blank=True, to='awards.AwardManager', null=True)),
                ('who_is_prime', models.ForeignKey(verbose_name=b'Prime Sponsor', blank=True, to='awards.PrimeSponsor', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalIntake',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(verbose_name=b'Comments', blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created', null=True)),
                ('agency', models.CharField(max_length=255, blank=True)),
                ('prime_sponsor', models.CharField(max_length=255, verbose_name=b'Prime (if GW is subawardee)', blank=True)),
                ('program_announcement', models.CharField(max_length=50, verbose_name=b'Program announcement number', blank=True)),
                ('announcement_link', models.CharField(max_length=250, blank=True)),
                ('proposal_due_to_sponsor', models.DateField(null=True, blank=True)),
                ('proposal_due_to_ovpr', models.DateField(null=True, verbose_name=b'Proposal due to OVPR', blank=True)),
                ('proposal_due_to_aor', models.DateField(null=True, verbose_name=b'Proposal due to AOR', blank=True)),
                ('spa1', models.CharField(max_length=150, null=True, verbose_name=b'SPA I*', choices=[('Aileen Miller', 'Aileen Miller'), ('Alma Starks', 'Alma Starks'), ('Anna Mansueto', 'Anna Mansueto'), ('Aquinos Butler', 'Aquinos Butler'), ('Asirinaidu Paidi', 'Asirinaidu Paidi'), ('ATP Admin', 'ATP Admin'), ('Begai Johnson', 'Begai Johnson'), ('Carolyn Harvey', 'Carolyn Harvey'), ('Catherine Summers', 'Catherine Summers'), ('Charles Maples', 'Charles Maples'), ('Chris Marchak', 'Chris Marchak'), ('Christine Kim', 'Christine Kim'), ('Dagmar Christensen', 'Dagmar Christensen'), ('Deborah Pomerantz', 'Deborah Pomerantz'), ('DIT Service', 'DIT Service'), ('Edward McKoy', 'Edward McKoy'), ('Emmett Scott', 'Emmett Scott'), ('Gina Lohr', 'Gina Lohr'), ('J. Akua Harris', 'J. Akua Harris'), ('Jamal Brooks', 'Jamal Brooks'), ('Jennifer Strickland', 'Jennifer Strickland'), ('Jennifer Liasson', 'Jennifer Liasson'), ('Jessica Harb', 'Jessica Harb'), ('Joyce Webster', 'Joyce Webster'), ('Kai-Kong Chan', 'Kai-Kong Chan'), ('Karen Johnson', 'Karen Johnson'), ('Katheryne Angevine', 'Katheryne Angevine'), ('Kenrick Kennedy', 'Kenrick Kennedy'), ('Latanya Carter', 'Latanya Carter'), ('Lily Gebru', 'Lily Gebru'), ("Lisa O'Neill", "Lisa O'Neill"), ('Lorenzo Miles', 'Lorenzo Miles'), ('Margaret Roldan', 'Margaret Roldan'), ('Mark Stevens', 'Mark Stevens'), ('Mary Milbauer', 'Mary Milbauer'), ('Megan Dieleman', 'Megan Dieleman'), ('Michael Wolf', 'Michael Wolf'), ('Michael Ng', 'Michael Ng'), ('Michelle Hall', 'Michelle Hall'), ('Monique Foxx', 'Monique Foxx'), ('Myrna Alonzo', 'Myrna Alonzo'), ('Nartasha Richards', 'Nartasha Richards'), ('Nasra Abdi', 'Nasra Abdi'), ('Nasrin Khoshand', 'Nasrin Khoshand'), ('Natalie Linear', 'Natalie Linear'), ('Neg Watling', 'Neg Watling'), ('Ofelia Olsen', 'Ofelia Olsen'), ('Rachma Saukani', 'Rachma Saukani'), ('Radojka Faguy', 'Radojka Faguy'), ('Rita Dikdan', 'Rita Dikdan'), ('Robert Harrison', 'Robert Harrison'), ('Robert Donnally', 'Robert Donnally'), ('Robert Pitysingh', 'Robert Pitysingh'), ('Shandra White', 'Shandra White'), ('Steven Arledge', 'Steven Arledge'), ('Sylvia Ezekilova', 'Sylvia Ezekilova'), ('Test User', 'Test User'), ('Tracy Clark', 'Tracy Clark')])),
                ('school', models.CharField(max_length=150, blank=True)),
                ('phs_funded', models.NullBooleanField(verbose_name=b'PHS funded?')),
                ('fcoi_submitted', models.NullBooleanField(verbose_name=b'FCOI disclosure submitted for each investigator?')),
                ('date_received', models.DateField(null=True, verbose_name=b'Date received by SPA I', blank=True)),
                ('proposal_status', models.CharField(blank=True, max_length=2, choices=[(b'NS', b'Cancelled - not submitted'), (b'PE', b'Planned'), (b'RO', b'Routing'), (b'SB', b'Submitted')])),
                ('proposal_outcome', models.CharField(blank=True, max_length=2, choices=[(b'AW', b'Awarded'), (b'UN', b'Unfunded')])),
                ('proposal_number', models.CharField(max_length=15, verbose_name=b'Cayuse Proposal Number', blank=True)),
                ('five_days_requested', models.DateField(null=True, verbose_name=b'Date 5 days waiver requested', blank=True)),
                ('five_days_granted', models.DateField(null=True, verbose_name=b'Date 5 days waiver granted', blank=True)),
                ('jit_request', models.NullBooleanField(verbose_name=b'JIT request?')),
                ('jit_response_submitted', models.DateField(null=True, verbose_name=b'JIT response submitted?', blank=True)),
                ('five_days_waiver_request', models.NullBooleanField(verbose_name=b'5 day waiver granted?')),
                ('award', models.OneToOneField(null=True, blank=True, to='awards.Award')),
                ('department', models.ForeignKey(verbose_name=b'Department', blank=True, to='awards.AwardOrganization', null=True)),
                ('principal_investigator', models.ForeignKey(verbose_name=b'Principal Investigator', blank=True, to='awards.AwardManager', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PTANumber',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('project_number', models.CharField(max_length=100, verbose_name=b'Project #', blank=True)),
                ('task_number', models.CharField(max_length=100, verbose_name=b'Task #', blank=True)),
                ('award_number', models.CharField(max_length=100, verbose_name=b'Award #', blank=True)),
                ('award_setup_complete', models.DateField(null=True, verbose_name=b'Award Setup Complete', blank=True)),
                ('total_pta_amount', models.DecimalField(null=True, verbose_name=b'Total PTA Amt', max_digits=10, decimal_places=2, blank=True)),
                ('parent_banner_number', models.CharField(max_length=100, verbose_name=b'Prnt Banner #', blank=True)),
                ('banner_number', models.CharField(max_length=100, verbose_name=b'Banner #', blank=True)),
                ('cs_banner_number', models.CharField(max_length=100, verbose_name=b'CS Banner #', blank=True)),
                ('project_title', models.CharField(max_length=256, verbose_name=b'Project Title*', blank=True)),
                ('eas_award_type', models.CharField(blank=True, max_length=2, verbose_name=b'EAS Award Type*', choices=[(b'C', b'Contract'), (b'G', b'Grant'), (b'I', b'Internal Funding'), (b'PP', b'Per Patient'), (b'PA', b'Pharmaceutical')])),
                ('preaward_date', models.DateField(null=True, blank=True)),
                ('start_date', models.DateField(null=True, verbose_name=b'Start Date*', blank=True)),
                ('end_date', models.DateField(null=True, verbose_name=b'End Date*', blank=True)),
                ('final_reports_due_date', models.DateField(null=True, verbose_name=b'Final Reports/Final Invoice Due Date (Close Date)*', blank=True)),
                ('sp_type', models.CharField(blank=True, max_length=3, verbose_name=b'SP Type*', choices=[(b'SP1', b'SP1 - Research and Development'), (b'SP2', b'SP2 - Training'), (b'SP3', b'SP3 - Other'), (b'SP4', b'SP4 - Clearing and Suspense'), (b'SP5', b'SP5 - Program Income'), (b'SP7', b'SP7 - Symposium/Conference/Seminar')])),
                ('short_name', models.CharField(max_length=30, verbose_name=b'Award Short Name*', blank=True)),
                ('agency_award_number', models.CharField(max_length=50, verbose_name=b'Agency Award Number*', blank=True)),
                ('sponsor_award_number', models.CharField(max_length=50, verbose_name=b'Prime Award # (if GW is subawardee)*', blank=True)),
                ('sponsor_banner_number', models.CharField(max_length=50, blank=True)),
                ('eas_status', models.CharField(blank=True, max_length=2, verbose_name=b'EAS Status*', choices=[(b'A', b'Active'), (b'OH', b'On hold'), (b'AR', b'At risk'), (b'C', b'Closed')])),
                ('ready_for_eas_setup', models.CharField(blank=True, max_length=3, verbose_name=b'Ready for EAS Setup?', choices=[(b'Y', b'Yes'), (b'N', b'No'), (b'M', b'Manual')])),
                ('is_edited', models.BooleanField(default=False)),
                ('pta_number_updated', models.DateField(null=True, blank=True)),
                ('agency_name', models.ForeignKey(verbose_name=b'Agency Name*', blank=True, to='awards.FundingSource', null=True)),
                ('allowed_cost_schedule', models.ForeignKey(verbose_name=b'Allowed Cost Schedule*', blank=True, to='awards.AllowedCostSchedule', null=True)),
                ('award', models.ForeignKey(to='awards.Award')),
                ('award_template', models.ForeignKey(verbose_name=b'Award Template*', blank=True, to='awards.AwardTemplate', null=True)),
                ('cfda_number', models.ForeignKey(verbose_name=b'CFDA number*', blank=True, to='awards.CFDANumber', null=True)),
                ('department_name', models.ForeignKey(verbose_name=b'Department Code & Name*', blank=True, to='awards.AwardOrganization', null=True)),
                ('federal_negotiated_rate', models.ForeignKey(verbose_name=b'Federal Negotiated Rate*', blank=True, to='awards.FedNegRate', null=True)),
                ('indirect_cost_schedule', models.ForeignKey(verbose_name=b'Indirect Cost Schedule*', blank=True, to='awards.IndirectCost', null=True)),
                ('principal_investigator', models.ForeignKey(verbose_name=b'PI*', blank=True, to='awards.AwardManager', null=True)),
                ('who_is_prime', models.ForeignKey(blank=True, to='awards.PrimeSponsor', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('report', models.CharField(blank=True, max_length=2, choices=[(b'TA', b'Technical Annual'), (b'TS', b'Technical Semiannual'), (b'TQ', b'Technical Quarterly'), (b'IP', b'Interim Progress Report (Non-Competing Continuations)'), (b'DL', b'Deliverables'), (b'IP', b'Invention/Patent Annual'), (b'PA', b'Property Annual'), (b'EA', b'Equipment Annual')])),
                ('due_date', models.DateField(null=True, blank=True)),
                ('submitted_date', models.DateField(null=True, blank=True)),
                ('award', models.ForeignKey(to='awards.Award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subaward',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('comments', models.TextField(verbose_name=b'Comments', blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Date Created', null=True)),
                ('recipient', models.CharField(max_length=250, blank=True)),
                ('agreement_type', models.CharField(blank=True, max_length=2, choices=[(b'SA', b'Subaward'), (b'SC', b'Subcontract'), (b'IC', b'ICA'), (b'M', b'Modification'), (b'H', b'Honorarium'), (b'C', b'Consultant'), (b'CS', b'Contract Service')])),
                ('modification_number', models.CharField(max_length=50, blank=True)),
                ('subrecipient_type', models.CharField(blank=True, max_length=2, verbose_name=b'Subrecipient Type', choices=[(b'F', b'Foundation'), (b'FP', b'For-Profit'), (b'SG', b'State Government'), (b'LG', b'Local Government'), (b'I', b'International'), (b'ON', b'Other non-profit'), (b'U', b'University')])),
                ('assist', models.CharField(max_length=100, blank=True)),
                ('date_received', models.DateField(null=True, blank=True)),
                ('status', models.CharField(blank=True, max_length=2, choices=[(b'R', b'Review'), (b'G', b'Waiting for GCAS approval'), (b'D', b'Waiting for Department'), (b'P', b'Procurement'), (b'S', b'Sent to recepient')])),
                ('risk', models.CharField(blank=True, max_length=2, choices=[(b'L', b'Low'), (b'M', b'Medium'), (b'H', b'High')])),
                ('approval_expiration', models.DateField(null=True, verbose_name=b'Date of Expiration for Approval', blank=True)),
                ('subaward_ready', models.DateField(null=True, verbose_name=b'Subaward ready to be initiated', blank=True)),
                ('sent', models.DateField(null=True, verbose_name=b'Subagreement sent to recipient', blank=True)),
                ('reminder', models.NullBooleanField(verbose_name=b'Reminder sent to Subawardee?')),
                ('received', models.DateField(null=True, verbose_name=b'Receipt of Partially Executed Subagreement', blank=True)),
                ('fcoi_cleared', models.DateField(null=True, verbose_name=b'Subaward Cleared FCOI Procedures', blank=True)),
                ('citi_cleared', models.DateField(null=True, verbose_name=b'Subaward Completed CITI Training', blank=True)),
                ('date_fully_executed', models.DateField(null=True, blank=True)),
                ('amount', models.DecimalField(null=True, verbose_name=b'Subaward Total Amount', max_digits=10, decimal_places=2, blank=True)),
                ('gw_number', models.CharField(max_length=50, verbose_name=b'GW Subaward Number', blank=True)),
                ('funding_mechanism', models.CharField(blank=True, max_length=2, verbose_name=b'Funding mechanism', choices=[(b'FP', b'Fixed price subcontract'), (b'CR', b'Cost-reimbursable subcontract'), (b'FA', b'Fixed amount award'), (b'OT', b'Other')])),
                ('other_mechanism', models.CharField(max_length=255, verbose_name=b'Other funding mechanism', blank=True)),
                ('contact_information', models.TextField(verbose_name=b'Subawardee contact information', blank=True)),
                ('zip_code', models.CharField(max_length=50, verbose_name=b'ZIP code', blank=True)),
                ('subaward_start', models.DateField(null=True, verbose_name=b'Subaward Performance Period Start', blank=True)),
                ('subaward_end', models.DateField(null=True, verbose_name=b'Subaward Performance Period End', blank=True)),
                ('debarment_check', models.NullBooleanField(verbose_name=b'Debarment or suspension check?')),
                ('international', models.NullBooleanField(verbose_name=b'International?')),
                ('cfda_number', models.CharField(max_length=50, verbose_name=b'CFDA number', blank=True)),
                ('fain', models.CharField(max_length=50, verbose_name=b'FAIN', blank=True)),
                ('ein', models.CharField(max_length=50, verbose_name=b'EIN', blank=True)),
                ('duns_number', models.CharField(max_length=50, verbose_name=b'DUNS number', blank=True)),
                ('ffata_reportable', models.NullBooleanField(verbose_name=b'FFATA Reportable?')),
                ('ffata_submitted', models.DateField(null=True, verbose_name=b'FFATA Report Submitted Date', blank=True)),
                ('tech_report_due', models.DateField(null=True, verbose_name=b'Technical Report Due Date', blank=True)),
                ('tech_report_received', models.DateField(null=True, verbose_name=b'Technical Report Received Date', blank=True)),
                ('subaward_completion_date', models.DateTimeField(null=True, verbose_name=b'Completion Date', blank=True)),
                ('award', models.ForeignKey(to='awards.Award')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='performancesite',
            name='proposal',
            field=models.ForeignKey(to='awards.Proposal'),
        ),
        migrations.AddField(
            model_name='keypersonnel',
            name='proposal',
            field=models.ForeignKey(to='awards.Proposal'),
        ),
        migrations.AlterUniqueTogether(
            name='easmapping',
            unique_together=set([('interface', 'field', 'incoming_value', 'atp_model', 'atp_pk')]),
        ),
        migrations.AddField(
            model_name='awardsetup',
            name='award_template',
            field=models.ForeignKey(blank=True, to='awards.AwardTemplate', null=True),
        ),
        migrations.AddField(
            model_name='awardsetup',
            name='cfda_number',
            field=models.ForeignKey(verbose_name=b'CFDA number', blank=True, to='awards.CFDANumber', null=True),
        ),
        migrations.AddField(
            model_name='awardsetup',
            name='federal_negotiated_rate',
            field=models.ForeignKey(blank=True, to='awards.FedNegRate', null=True),
        ),
        migrations.AddField(
            model_name='awardsetup',
            name='indirect_cost_schedule',
            field=models.ForeignKey(blank=True, to='awards.IndirectCost', null=True),
        ),
        migrations.AddField(
            model_name='awardmodification',
            name='award_template',
            field=models.ForeignKey(blank=True, to='awards.AwardTemplate', null=True),
        ),
        migrations.AddField(
            model_name='awardmodification',
            name='cfda_number',
            field=models.ForeignKey(verbose_name=b'CFDA number', blank=True, to='awards.CFDANumber', null=True),
        ),
        migrations.AddField(
            model_name='awardmodification',
            name='federal_negotiated_rate',
            field=models.ForeignKey(blank=True, to='awards.FedNegRate', null=True),
        ),
        migrations.AddField(
            model_name='awardmodification',
            name='indirect_cost_schedule',
            field=models.ForeignKey(blank=True, to='awards.IndirectCost', null=True),
        ),
        migrations.AlterIndexTogether(
            name='proposal',
            index_together=set([('award', 'is_first_proposal')]),
        ),
    ]
